### ISSUE TITLE
Iterating over data from assignment.get_gradeable_students() produces exception.

### ISSUE THREAD

**Issue by drdrewusaf** [ucfopen/canvasapi#389]
# Describe the bug

Iterating over the paginated list generated by `assignment.get_gradeable_students()` produces the following exception:
```
Exception "unhandled AttributeError"
'NoneType' object has no attribute 'group'
```

The debugger traces to `paginated_list.py` line 67:
`            re.search(regex, next_link["url"]).group(1) if next_link else None`

# To Reproduce

Iterate over the paginated list...
```
studentList = assignment.get_gradeable_students()
for s in studentList:
    print(s)
```

The problem also occurs when called directly in the loop...
```
for s in assignment.get_gradeable_students():
    print(s)
```

# Expected behavior

A printed list of `courseID-studentID` for each item in the paginated list.

# Environment information

- Python version 
```
$ python --version
Python 3.8.3
```

- CanvasAPI version 
```
$ pip show canvasapi
Name: canvasapi
Version: 0.16.0
Summary: API wrapper for the Canvas LMS
Home-page: https://github.com/ucfopen/canvasapi
Author: University of Central Florida - Center for Distributed Learning
Author-email: techrangers@ucf.edu
License: MIT License
Location: /usr/local/lib/python3.8/site-packages
Requires: six, pytz, requests
Required-by:
```

- re version for giggles
```
>>> import re as reg
>>> print(reg.__version__)
2.2.1
```

# Additional context

This call worked in CanvasAPI v0.15.0.  I tried to follow back through paginated_list.py, assignment.py, user.py, course.py, and canvas_object.py, but I am limited in my knowledge of both Python and Canvas.

**Comment by Thetwam** [comment]
Hey @drdrewusaf, thanks for the bug report. What does your `API_URL` look like?

Possibly related: #370

**Comment by drdrewusaf** [comment]
Good Afternoon @Thetwam!

My `API_URL` *was* the following when you requested it...
`https://lms.au.af.edu/`

That led me to remove the `/` at the end.  I may not be a great coder, but I know the challenges that come with things like regex.

With `https://lms.au.af.edu` as my `API_URL`, it's back to working again.

Thanks for the hint!  Not sure if that means this is a bug, or if it works like it's supposed to.


Andrew

**Comment by Thetwam** [comment]
No worries, @drdrewusaf! While the correct URL shouldn't have the trailing slash, we actually do have something in place to allow it to work. Unfortunately, we broke that in the latest release. See #390. Sorry about that!

**Comment by Thetwam** [comment]
@drdrewusaf Should be fixed in v0.16.1. Thanks for helping us track this one down!

Resolved in #391
